### ISSUE TITLE
Automate Build-Testing-Packaging

### ISSUE THREAD

**Issue by tomkerkhove** [CoditEU/Mjolnir#5]
Automate the release cycle.

- [x] Automate build
- [x] Automate testing
- [ ] Automate NuGet packaging

**Comment by tomkerkhove** [comment]
What NuGet packages do we want to offer?

My suggestion would be: 
- BizTalk<Extended> - Pipeline Components
- BizTalk<Extended> - Pipeline Components Extensions
- BizTalk<Extended> - Orchestration Extensions

**Comment by tomkerkhove** [comment]
`AssemblyFileVersion` can be used in conjunction with MyGet, we only need to update the attribute.
If you want we can ship the first version.

**Comment by samneirinck** [comment]
:shipit:

**Comment by tomkerkhove** [comment]
MyGet is configured.
